---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    redis_instance_enabled: false
  tasks:
    - name: "Remove Redis instance"
      ansible.builtin.import_role:
        name: "redis_instance"
