---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'mongodb' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mongodb"
      register: namespace_mongodb
      until:
        - namespace_mongodb.resources | length > 0
        - namespace_mongodb.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'mongodb' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_mongodb.resources | length > 0
          - namespace_mongodb.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'mongodb' is not active."

    - name: "Wait for 'mongodb-kubernetes-operator' deployment to be available."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "mongodb-kubernetes-operator"
        namespace: "mongodb"
      register: operator_deployment
      until:
        - operator_deployment.resources | length > 0
        - operator_deployment.resources[0].status.availableReplicas | default(0) == 1
      retries: 30
      delay: 5

    - name: "Assert that 'mongodb-kubernetes-operator' deployment is available."
      ansible.builtin.assert:
        that:
          - operator_deployment.resources | length > 0
          - operator_deployment.resources[0].status.availableReplicas | default(0) == 1
        fail_msg: "Deployment 'mongodb-kubernetes-operator' is not available."

    - name: "Wait for 'mongodb-instance' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mongodb-instance"
      register: db_namespace
      until:
        - db_namespace.resources | length > 0
        - db_namespace.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'mongodb-instance' namespace is active."
      ansible.builtin.assert:
        that:
          - db_namespace.resources | length > 0
          - db_namespace.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'mongodb-instance' is not active."

    - name: "Wait for 'mymongodb-mongodb-instance' StatefulSet to be available."
      kubernetes.core.k8s_info:
        kind: "StatefulSet"
        name: "mymongodb-mongodb-instance"
        namespace: "mongodb-instance"
      register: stateful_set
      until:
        - stateful_set.resources | length > 0
        - stateful_set.resources[0].status.availableReplicas | default(0) == 1
      retries: 30
      delay: 5

    - name: "Assert that 'mymongodb-mongodb-instance' StatefulSet is available."
      ansible.builtin.assert:
        that:
          - stateful_set.resources | length > 0
          - stateful_set.resources[0].status.availableReplicas | default(0) == 1
        fail_msg: "StatefulSet 'mymongodb-mongodb-instance' is not available."

    - name: "Wait for 'mymongodb-connection-string' secret to be created."
      kubernetes.core.k8s_info:
        kind: "Secret"
        name: "mymongodb-connection-string"
        namespace: "mongodb-instance"
      register: connection_secret
      until:
        - connection_secret.resources | length > 0
        - connection_secret.resources[0].data is defined
      retries: 30
      delay: 5

    - name: "Assert that 'mymongodb-connection-string' secret is created."
      ansible.builtin.assert:
        that:
          - connection_secret.resources | length > 0
          - connection_secret.resources[0].data is defined
        fail_msg: "Secret 'mymongodb-connection-string' is not created."

    - name: "Wait for 'mymongodb' admin password secret to be created."
      kubernetes.core.k8s_info:
        kind: "Secret"
        name: "mymongodb-mongodb-instance-mongo-admin-password"
        namespace: "mongodb-instance"
      register: admin_password_secret
      until:
        - admin_password_secret.resources | length > 0
        - admin_password_secret.resources[0].data is defined
      retries: 30
      delay: 5

    - name: "Assert that 'mymongodb' admin password secret is created."
      ansible.builtin.assert:
        that:
          - admin_password_secret.resources | length > 0
          - admin_password_secret.resources[0].data is defined
        fail_msg: "Secret 'mymongodb-mongodb-instance-mongo-admin-password' is not created."

    - name: "Wait for 'mymongodb' metrics password secret to be created."
      kubernetes.core.k8s_info:
        kind: "Secret"
        name: "mymongodb-mongodb-instance-metrics-endpoint-password"
        namespace: "mongodb-instance"
      register: metrics_password_secret
      until:
        - metrics_password_secret.resources | length > 0
        - metrics_password_secret.resources[0].data is defined
      retries: 30
      delay: 5

    - name: "Assert that 'mymongodb' metrics password secret is created."
      ansible.builtin.assert:
        that:
          - metrics_password_secret.resources | length > 0
          - metrics_password_secret.resources[0].data is defined
        fail_msg: "Secret 'mymongodb-mongodb-instance-metrics-endpoint-password' is not created."
