---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'postgres-operator' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "postgres-operator"
      register: namespace_postgres_operator
      until: namespace_postgres_operator.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'postgres-operator' namespace is removed."
      ansible.builtin.assert:
        that: namespace_postgres_operator.resources | length == 0
        fail_msg: "Namespace 'postgres-operator' is not removed."
