---
# @meta description: >
# Role to install Install Mongodb for Kubernetes operaror on a cluster.
# It install community operator via its helm chart and deploy mongodb replicatset.
# @end
galaxy_info:
  description: Install Mongodb for Kubernetes operaror
  role_name: mongodb_operator
  author: Clément Hubert

  license: MPL-2.0

  min_ansible_version: "2.17"

  galaxy_tags:
    - kubernetes
    - mongodb
    - operator

dependencies: []
