---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'mongodb' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mongodb"
      register: namespace_mongodb
      until: namespace_mongodb.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'mongodb' namespace is removed."
      ansible.builtin.assert:
        that: namespace_mongodb.resources | length == 0
        fail_msg: "Namespace 'mongodb' is not removed."
