---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'opensearch' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "opensearch"
      register: namespace_opensearch
      until: namespace_opensearch.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'opensearch' namespace is removed."
      ansible.builtin.assert:
        that: namespace_opensearch.resources | length == 0
        fail_msg: "Namespace 'opensearch' is not removed."
