---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'postgres-operator' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "postgres-operator"
      register: namespace_postgres_operator
      until:
        - namespace_postgres_operator.resources | length > 0
        - namespace_postgres_operator.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'postgres-operator' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_postgres_operator.resources | length > 0
          - namespace_postgres_operator.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'postgres-operator' is not active."

    - name: "Wait for 'postgres-operator' deployment to be available."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "postgres-operator"
        namespace: "postgres-operator"
      register: operator_deployment
      until:
        - operator_deployment.resources | length > 0
        - operator_deployment.resources[0].status.availableReplicas | default(0) == 1
      retries: 30
      delay: 5

    - name: "Assert that 'postgres-operator' deployment is available."
      ansible.builtin.assert:
        that:
          - operator_deployment.resources | length > 0
          - operator_deployment.resources[0].status.availableReplicas | default(0) == 1
        fail_msg: "Deployment 'postgres-operator' is not available."
