---
- name: "Update opensearch_cluster with overridden key"
  ansible.builtin.set_fact:
    opensearch_cluster: >-
      {{ opensearch_cluster | ansible.builtin.combine({
           value_to_update.key: value_to_update.value,
           'updated': true,
         }) }}
  changed_when: false
