---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build a kind cluster (wait for control plane).
      ansible.builtin.command: >-
        kind create cluster
        --wait 300s
        --name molecule-test
        --kubeconfig {{ kubeconfig }}
      changed_when: true

    - name: "Install MariaDB operator"
      ansible.builtin.import_role:
        name: "mariadb_operator"

    - name: "Install MariaDB instance"
      ansible.builtin.import_role:
        name: "mariadb_instance"
      vars:
        mariadb_instance_values_override:
          replicas: 1
          galera_enabled: false
