---
- name: "Uninstall MariaDB Operator helm package"
  kubernetes.core.helm:
    name: "{{ mariadb_operator_deployment_name }}"
    namespace: "{{ mariadb_operator_namespace }}"
    state: "absent"
    chart_ref: "{{ mariadb_operator_helm_chart_ref }}"
    chart_version: "{{ mariadb_operator_helm_chart_version }}"
    wait: true

- name: "Uninstall MariaDB Operator CRDs helm package"
  kubernetes.core.helm:
    name: "{{ mariadb_operator_crds_deployment_name }}"
    namespace: "{{ mariadb_operator_namespace }}"
    state: "absent"
    chart_ref: "{{ mariadb_operator_crds_helm_chart_ref }}"
    chart_version: "{{ mariadb_operator_crds_helm_chart_version }}"
    wait: true

- name: "Remove MariaDB Operator helm repo"
  kubernetes.core.helm_repository:
    name: "{{ mariadb_operator_helm_repo_name }}"
    repo_url: "{{ mariadb_operator_helm_repo_url }}"
    state: "absent"

- name: "Remove MariaDB Operator namespace"
  kubernetes.core.k8s:
    name: "{{ mariadb_operator_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "absent"
