---
- name: "Setup MariaDB Operator"
  ansible.builtin.include_tasks:
    file: "setup.yml"
    apply:
      tags:
        - "mariadb_operator"
        - "install"
  when: mariadb_operator_crds_enabled or mariadb_operator_enabled
  tags: ["always"]

- name: "Cleanup MariaDB Operator"
  ansible.builtin.include_tasks:
    file: "cleanup.yml"
    apply:
      tags:
        - "mariadb_operator"
        - "uninstall"
  when: not mariadb_operator_crds_enabled and not mariadb_operator_enabled
  tags: ["always"]
