---
name: Test roles

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'roles/**'
      - '.github/**'
      - devbox.json
      - devbox.lock
      - flake.nix
      - flake.lock
  pull_request:
    branches: [main]
    paths:
      - 'roles/**'
      - '.github/**'
      - devbox.json
      - devbox.lock
      - flake.nix
      - flake.lock

jobs:
  mariadb_instance:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "mariadb_instance"
  mariadb_operator:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "mariadb_operator"
  mongodb_instance:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "mongodb_instance"
  mongodb_operator:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "mongodb_operator"
  postgres_operator:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "postgres_operator"
  postgres_instance:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "postgres_instance"
  redis_operator:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "redis_operator"
  redis_instance:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "redis_instance"
